use LMS

Em um único SELECT exiba o nome, email e login do(s) alunos(s) que não possuem
nenhuma atividade cadastrada na tabela ENTREGA. Ordenado alfabeticamente pelo
nome do aluno.

SELECT
	ALUNO.NOME,
	ALUNO.EMAIL,
	USUARIO.LOGIN
FROM ENTREGA
	LEFT JOIN ALUNO ON ALUNO.ID = ENTREGA.IDALUNO
	LEFT JOIN USUARIO ON ALUNO.IDUSUARIO = USUARIO.ID 
	



SELECT * FROM ALUNO
SELECT * FROM EMAIL
SELECT * FROM USUARIO
SELECT * FROM ENTREGA

SELECT STATUS, NOTA, TITULO
FROM ENTREGA
WHERE STATUS = '0' AND NOTA = '0' AND TITULO ='0' AND STATUS IS NULL AND NOTA IS NULL AND TITULO IS NULL

SELECT campo1, campo2
FROM nome_tabela
WHERE campo1 = ''
OR campo1 IS NULL


SELECT
    PROFESSOR.NOME, 
    ENTREGA.DTENTREGA, 
    ENTREGA.TITULO, 
    ENTREGA.NOTA
FROM ENTREGA
    JOIN PROFESSOR ON PROFESSOR.ID = ENTREGA.IDPROFESSOR
    JOIN ALUNO ON ALUNO.ID = ENTREGA.IDALUNO
WHERE (ENTREGA.DTENTREGA BETWEEN '2015-01-01' AND '2015-06-30' AND ENTREGA.TITULO = 'AC 1' AND ENTREGA.NOTA = 2.00)



